export default {
  eracle: {
    n: 'Heracles', ep: 'Hero of strength, warder-off of evils',
    intro: 'Heracles is the greatest of the Greek heroes, son of Zeus and the mortal Alkmene, whose whole existence was marked by Hera’s hatred and by the labour of atoning for and overcoming trials. In a fit of madness sent by the goddess he killed his own children, and to purify himself he submitted to the service of King Eurystheus, performing the famous Twelve Labours: he killed the Nemean lion and the Hydra of Lerna, captured the Cerynean hind and the Erymanthian boar, cleaned the stables of Augeas, tamed the bull of Crete and the mares of Diomedes, won the belt of the Amazon and the cattle of Geryon, gathered the apples of the Hesperides and dragged Cerberus out of Hades. His strength was immense, but greater still was his capacity to endure and persevere. He died in flames, poisoned by the robe of the centaur Nessus, but the fire burned away only the mortal part and Zeus received him among the gods. For this he was venerated with a double nature, hero and divinity at once.',
    dom: ['Physical and moral strength', 'Courage under trial', 'Perseverance and resilience', 'Protection from evils (alexikakos)'],
    sim: ['Club', 'The skin of the Nemean lion', 'Bow', 'Wine kantharos'],
    off: ['Double sacrifices: part as to a god, part as to a hero', 'White poplar wood burned', 'Libations of wine and cakes', 'Roasted meats at the sacred banquet'],
    allora: 'Alone among the heroes, Heracles received a cult of double nature: in some places heroic and chthonic sacrifices were offered to him, poured onto the ground for the dead beneath, in others divine honours as to an Olympian god. The oldest centre of the cult was Thebes, his native city, but sanctuaries, altars and games dedicated to him rose all over Greece. As Alexikakos, "he who wards off evils", he was invoked in defence of houses and cities against misfortune.',
    adesso: 'Invoke him as patron of strength, resilience and perseverance in the face of the "labours" of daily life, those trials that seem never to end. When you face a difficulty that demands tenacity, ask him for the courage to go on one step at a time. An altar with the club or the lion skin and a libation of wine suits the request for inner strength. He is the patron of those who do not give up.',
  },

  teseo: {
    n: 'Theseus', ep: 'National hero of Athens',
    intro: 'Theseus is the hero Athens chose as its champion and symbol, son of King Aegeus (or of the god Poseidon) and of Aithra. Raised far from his father, as soon as he was strong enough to lift the rock under which his father’s sword and sandals lay hidden, he set out for Athens by the dangerous land route, ridding the isthmus of brigands and monsters such as Procrustes and Periphetes, whose club he took. But his most famous exploit was the descent into the Labyrinth of Crete, where he killed the Minotaur and came out again thanks to the thread Ariadne had given him. Returning to Athens, he forgot to raise the white sails, and his father Aegeus, believing him dead, threw himself into the sea. Having become king, Theseus united Attica into a single state by the synoecism and was remembered as the founder of the city and the first guarantor of its institutions. His figure embodied civic courage and the defence of the weak.',
    dom: ['Protection of Athens', 'Civic courage', 'Defence of the young and the oppressed', 'Refuge for those seeking asylum'],
    sim: ['His father’s sword and sandals', 'The club of Periphetes', 'Ariadne’s thread', 'The black ship'],
    off: ['Sacrifices on the 8th of every month (a number sacred to him, as to Poseidon)', 'Chthonic offerings poured onto the ground', 'Heroic libations and cakes'],
    allora: 'After his death Theseus was honoured as the protecting hero of Athens; the general Kimon, following an oracle, brought back from the island of Skyros what were believed to be his bones and raised him the Theseion, which became a sacred asylum for slaves and the oppressed seeking refuge. The Theseia were celebrated in his honour, with sacrifices and games, and heroic rites were offered to him on the eighth day of every month, a number sacred to him and to Poseidon. He was felt to be the very patron of Athenian identity.',
    adesso: 'Honour him as patron of justice, of civic courage and of the defence of the weakest, and invoke him when you must take a stand for what is right. He is also the ideal guide in inner "labyrinths": ask him for the thread that helps you find your bearings in difficult choices and find the way out. A concrete act of solidarity towards someone in difficulty is the most genuine way of honouring him. He gives you the strength to face trials with a sense of community.',
  },

  perseo: {
    n: 'Perseus', ep: 'Vanquisher of the Gorgon',
    intro: 'Perseus is the hero who defeated the impossible and faced the gaze that turns to stone, son of Zeus and of Danaë, the princess the god reached in the form of a shower of gold. Shut as a newborn into a chest cast into the sea together with his mother, he was saved and grew up on the island of Seriphos, until King Polydektes, to be rid of him, sent him on an errand that seemed certain death: to bring back the head of Medusa, the Gorgon whose gaze turned every living being to stone. Helped by Athena and Hermes, he obtained the winged sandals, the helm of invisibility of Hades and the adamantine sickle, and managed to behead Medusa by looking only at her reflection on his polished shield. On the way back, with the head that still petrified, he freed Andromeda, chained to a rock as prey for a sea monster, and took her as his wife. The Gorgon’s head, given to Athena, became the apotropaic emblem above all others. His story taught how to defeat fear with cunning and courage.',
    dom: ['Courage in the face of fear', 'Protection against evil and the evil eye', 'Victory over the impossible', 'Cunning and ingenuity'],
    sim: ['The Gorgon’s head', 'Adamantine sickle (harpe)', 'Helm of invisibility', 'Winged sandals'],
    off: ['Heroic sacrifices and libations', 'Chthonic offerings poured onto the ground', 'Votive gifts in the heroa'],
    allora: 'Perseus was venerated as a hero at Seriphos, at Mycenae — the city tradition credited him with founding — at Argos and at Athens, where heroa were dedicated to him. The Gorgon’s head, the Gorgoneion, became a most powerful apotropaic symbol, carved on doors, shields, walls and coins to drive off evil and the evil eye. Sacrifices and votive gifts were offered to him in the heroa, according to the rites due to a hero.',
    adesso: 'Honour him as patron of courage and protection: you may keep an image of the Gorgoneion as an amulet against negative energies and fears. Invoke him above all when you face a fear that paralyses you, remembering that he did not look the monster in the face, but knew how to confront it by cunning, in reflection. Ask him for the clarity not to let yourself be turned to stone by fear, but to find the way past it. He is the patron of those who defeat what seems unbeatable.',
  },

  asclepio: {
    n: 'Asklepios', ep: 'God-hero of healing',
    intro: 'Asklepios is the great healer, son of Apollo and the mortal Koronis, whose medical art was so perfect that it crossed the very bounds of life. Snatched still in the womb from his dying mother upon the pyre, he was entrusted to the wise centaur Cheiron, who taught him the secrets of herbs and of medicine. Becoming a physician without equal, he even learned to raise the dead — thanks, it is said, to the Gorgon’s blood given him by Athena — and this disturbed the order of the cosmos: Zeus, fearing that mortals might escape death, struck him with the thunderbolt. But afterwards, to make amends or to acknowledge his merits, he raised him among the stars and among the gods, making him the power of medicine. His staff with the serpent coiled about it is still today the symbol of the medical art. Father of daughters such as Hygieia (Health) and Panakeia, he was the hope of every sick person in the ancient world.',
    dom: ['Health and healing', 'Care of body and mind', 'Healing dreams (incubation)', 'Medicine'],
    sim: ['Staff with the serpent', 'Sacred serpent', 'Dog', 'Laurel crown'],
    off: ['Sacrifice of a cockerel', 'Incubation: sleeping in the temple for a healing dream', 'Votive offerings of healed body parts', 'Honey cakes and libations'],
    allora: 'The cult of Asklepios had its most famous centre at Epidauros, and from there spread to the Asklepieia of Kos, Pergamon, Athens and the whole Greek world. Its most characteristic rite was incubation: the sick slept within the sacred precinct hoping the god would appear to them in a dream to indicate the cure or to heal them directly. Those who were healed offered votive images of the mended parts of the body and sacrificed a cockerel, as even Socrates recalls in his last words.',
    adesso: 'He is the patron of health above all others: invoke him before an operation, during an illness, or for the healing of someone dear to you. You may dedicate a small offering to him before falling asleep, asking for dreams that show you the way to healing, of body or of spirit. An act of care towards yourself or towards someone ill is already a way of honouring him. He stands for the hope of healing and the art of those who care.',
  },

  dioscuri: {
    n: 'The Dioskouroi', ep: 'Twin saviours of travellers',
    intro: 'The Dioskouroi, Kastor and Polydeukes, are the shining twins who rush to save those in danger, at sea and in battle. Sons of Leda, they were born of a singular circumstance: Polydeukes, begotten by Zeus, was immortal, while Kastor, son of the mortal Tyndareos, was destined to die. Raised together, Kastor excelled at breaking horses and Polydeukes at boxing, and they took part in great enterprises, such as the hunt of the Calydonian boar and the expedition of the Argonauts. When Kastor fell in a feud, Polydeukes, in despair, would not enjoy immortality alone and begged Zeus to share his own lot with his brother: so the two twins alternate their existence, one day among the gods of Olympus, one day in the darkness of Hades. Changed at last into the constellation of the Twins, they appear to sailors as St Elmo’s fire, twin lights that announce salvation. They are the purest image of brotherly love and faithfulness.',
    dom: ['Protection at sea and on journeys', 'Rescue in battle', 'Patrons of horsemen and athletes', 'Hospitality and brotherly love'],
    sim: ['Two stars or caps (pileoi)', 'White horses', 'Spears', 'St Elmo’s fire'],
    off: ['Theoxenia: a banquet with a table laid to receive them as guests', 'Sacrifices in harbours and hippodromes', 'Libations for a safe return'],
    allora: 'Their cult was born at Sparta, where they were venerated as protectors of the city and symbolised by the dokana, two beams of wood joined together, and it spread afterwards through the whole Greek and Roman world. They were honoured with the Theoxenia, sacred banquets at which a table was laid to receive them as divine guests. They appeared to sailors in storms as twin lights of salvation and to horsemen in battle on white horses, and received sacrifices in harbours and hippodromes.',
    adesso: 'They are the ideal patrons of travellers: invoke them before setting out, for safety by air, by road or by sea, and for those you love who are far from home. You may light two twin lights and offer a symbolic meal, in the spirit of the ancient Theoxenia, as a sign of hospitality and a request for protection. Turn to them also to strengthen brotherly bonds and faithful friendships. They watch over wayfarers and over those who support one another.',
  },

  achille: {
    n: 'Achilles', ep: 'The greatest hero of Troy',
    intro: 'Achilles is the warrior without equal of the Trojan War, son of the mortal Peleus and of the sea goddess Thetis, who tried to make him invulnerable by dipping him in the waters of the Styx, holding him by the heel that thus remained his only weak point. He knew, by prophecy, that he had to choose between a long and obscure life and a short but glorious one, and he chose glory. The Iliad is born of his wrath: insulted by King Agamemnon, who took from him the captive Briseis, he withdrew from the battle, and only the death of his beloved companion Patroklos, killed by Hektor, brought him back raging to the field. He avenged his friend by killing Hektor and dragged his body around the walls, until old King Priam came to beg him to give back his son’s corpse, in one of the most moving scenes of the poem. Achilles himself fell soon after, struck in the heel by an arrow of Paris guided by Apollo. He embodied absolute valour and the tragic awareness of mortality.',
    dom: ['Valour in battle', 'Warrior strength', 'Loyalty to friends', 'Protection of those who sail the Black Sea'],
    sim: ['Ash spear from Mount Pelion', 'Shield forged by Hephaestus', 'Plumed helmet', 'The heel'],
    off: ['Night sacrifices at the burial mound', 'Libations of wine, honey and milk poured onto the ground', 'Victims wholly burned (heroic holocaust)'],
    allora: 'A half-divine hero, Achilles was venerated at the mound of Sigeion, near Troy, where sailors stopped to pay him honour, and above all as lord of the White Island, Leuke, in the Black Sea, where tradition held he had been carried after death to live a second heroic existence. He received night sacrifices and holocausts, victims wholly burned according to the chthonic rite, and funeral games in his honour. The sailors of the Euxine invoked him as protector of their routes.',
    adesso: 'Honour him as patron of valour and of excellence, the arete the Greeks admired above all things, and invoke him when you face a challenge that demands absolute courage and total dedication. A libation at sunset, poured onto the ground, can accompany the request for inner strength and for faithfulness to friends, virtues dear to him until death. Remember his tragic lesson too: glory has a price, and faithfulness to those we love counts for more than victory. He is the patron of those who give all of themselves.',
  },

  orfeo: {
    n: 'Orpheus', ep: 'Divine singer and master of the mysteries',
    intro: 'Orpheus is the singer whose music had power over the whole world, son of the Muse Kalliope and of a Thracian king, or of Apollo himself. When he took up the lyre and sang, wild beasts grew tame, trees bent down, stones moved and even rivers stopped to listen. He took part in the expedition of the Argonauts, and with his song overcame the deadly call of the Sirens. But the myth that made him immortal is that of Eurydice, his beloved wife dead of a serpent’s bite: Orpheus went down alive into Hades and with his music moved even Hades and Persephone, who granted him to bring her back to the light, provided he did not turn to look at her before going out. At the last step, overcome by the anxiety of love, he turned, and lost her forever. Torn with grief, he died dismembered by the Maenads, but his head went on singing and prophesying. He became the legendary founder of the Orphic mysteries, master of a path of purification of the soul.',
    dom: ['Music and poetry', 'Initiation into the mysteries', 'Knowledge of the beyond', 'Purification of the soul'],
    sim: ['Lyre', 'Crown of flowers', 'Animals tamed by song', 'The scroll of sacred verses'],
    off: ['Orphic rites with bloodless libations', 'Honey, milk and water (refusal of blood sacrifice)', 'Sung hymns and purifications'],
    allora: 'A Thracian singer, Orpheus was held to be the founder of the Orphic mysteries, a religious current that taught a doctrine of the soul, of its fall into the body and of its purification through rites and a life of abstinence. His head, according to legend, floated as far as Lesbos, where it went on prophesying from an oracle. The Orphics followed purifications, refused blood sacrifice and offered bloodless libations of honey, milk and water, accompanied by sung hymns.',
    adesso: 'He is the patron of musicians, poets and of anyone seeking an inner, spiritual path. Honour him with music, with the singing of hymns and with meditation, asking him for inspiration and guidance in the growth of the soul. Turn to him also in bereavement, for he knew the most painful loss and made song of it: his story teaches how to turn grief into beauty. A moment of recollection with the music you love is already homage to him.',
  },

  bellerofonte: {
    n: 'Bellerophon', ep: 'Tamer of Pegasus',
    intro: 'Bellerophon is the hero who tamed the winged horse and faced an unbeatable monster, a prince of Corinth, son of Glaukos (or of the god Poseidon). His most famous exploit was taming Pegasus, the winged horse born from the blood of Medusa, which he achieved thanks to the golden bridle given him by the goddess Athena, who appeared to him in a dream. Mounted on Pegasus he faced the Chimaera, the fire-vomiting monster with the body of a lion, the tail of a serpent and the head of a goat, and killed it from above by driving into its throat a spear tipped with lead, which the beast’s own fire melted and so choked it. He performed other victorious deeds for the king of Lycia, who had laid those deadly traps for him, and in the end married his daughter. But good fortune made him proud: he wished to rise into the sky with Pegasus as far as the dwelling of the gods, and Zeus, to punish his presumption, made the horse rear. Bellerophon fell and ended his days blind and alone, wandering in disgrace. His story is at once a triumph and a warning.',
    dom: ['Taming untameable forces', 'Courage in impossible undertakings', 'Protection from monsters', 'Ambition and its limit'],
    sim: ['Pegasus, the winged horse', 'Lead-tipped spear', 'Athena’s golden bridle', 'The Chimaera'],
    off: ['Sacrifices and libations in the temenos at Corinth', 'Chthonic offerings poured onto the ground', 'Votive gifts to Athena Chalinitis'],
    allora: 'Bellerophon was venerated as a hero at Corinth, his homeland, where a sacred precinct was dedicated to him in the grove of Kraneion, and honoured also in Lycia, the scene of his exploits. At Corinth Athena Chalinitis, "of the bridle", was venerated in memory of the golden bridle with which the hero had tamed Pegasus, and votive gifts were offered to her. Heroic sacrifices and libations were rendered to him, according to the rites due to heroes.',
    adesso: 'Honour him as patron of ambitious courage and of mastery over your own powers, invoking him before an undertaking that seems beyond you. His story teaches that, with the right help and determination, even the most frightening "chimaeras" can be defeated. But always remember the warning of his fall: do not let success turn into boundless pride. He gives you the drive to dare, and the wisdom to know your limits.',
  },

  atalanta: {
    n: 'Atalanta', ep: 'Huntress and runner',
    intro: 'Atalanta is the untameable heroine who chose the freedom of the woods, abandoned at birth by a father who wanted a son and suckled by a she-bear sent by Artemis. Raised wild among hunters, she became swift and strong as no man was, vowed to virginity after the example of the goddess. When the giant Calydonian boar was laying waste the countryside, she joined the greatest heroes in the hunt and it was she who first wounded the beast, drawing its first blood and earning the trophy, which her admirer Meleager granted her. In running she was unbeatable, and to escape marriage she imposed a deadly contest on her suitors: whoever beat her would marry her, whoever lost would die. No one outran her, until Hippomenes (or Melanion), with Aphrodite’s help, let three golden apples fall along the course: Atalanta stopped to gather them and lost the race, and with it her freedom. Her story celebrates female strength and self-determination.',
    dom: ['Hunting and athletics', 'Running and physical strength', 'Female independence', 'Self-determination'],
    sim: ['Bow and arrows', 'Hunting spear', 'The three golden apples', 'Wild animal skin'],
    off: ['Votive offerings from the hunt (often with Artemis)', 'Libations and gifts at sacred places', 'First fruits of the hunt'],
    allora: 'Atalanta’s figure was closely bound to the cult of Artemis, the virgin goddess of the hunt whose wild and free spirit she embodied. Remembered for the Calydonian hunt and for her running contests, she was honoured in places of Arcadia and Boeotia, which disputed her origin, with votive offerings from the hunt and first fruits. Her image recurred in art as a model of female athletic strength and courage.',
    adesso: 'She is the patron of women athletes, of hunters, and of anyone who defends their independence and their own nature. Invoke her for physical strength, for fair competition and for the courage not to betray who you are, even when the world would have you otherwise. Her story is a reminder of how precious it is to stay faithful to your freedom and not to be distracted by "golden apples" that make us lose the race. She gives you determination and pride.',
  },

  giasone: {
    n: 'Jason', ep: 'Leader of the Argonauts',
    intro: 'Jason is the hero who managed to gather the greatest champions of Greece into a single undertaking, a Thessalian prince deprived of the throne of Iolkos by his usurping uncle Pelias. Raised in secret by the centaur Cheiron, he returned to claim the kingdom, and along the way, having lost a sandal while helping an old woman — the goddess Hera in disguise — he presented himself wearing only one, fulfilling an oracle Pelias feared. His uncle, to be rid of him, imposed on him the apparently impossible mission of bringing back the Golden Fleece from far-off Colchis. Jason had the ship Argo built and gathered a crew of legendary heroes — the Argonauts, among them Heracles, Orpheus, the Dioskouroi and Atalanta — facing a thousand dangers with them: the Symplegades, the Harpies, hostile peoples. In Colchis he won the Fleece thanks to the help of the sorceress Medea, the king’s daughter, who fell in love with him and saved him from deadly trials. His name remains bound to the courage of the collective undertaking and to the voyage that opened up the world.',
    dom: ['Collective undertakings', 'Sea voyages', 'Leading a group', 'Pursuing a shared goal'],
    sim: ['The Golden Fleece', 'The ship Argo', 'A single sandal', 'Spear'],
    off: ['Libations and heroic sacrifices for a favourable voyage', 'Offerings to the sea divinities before departure', 'Votive gifts along the routes'],
    allora: 'The legend of Jason and the Argonauts was among the oldest and best loved in Greece, and it traced in imagination the routes of Greek navigation and settlement in the Mediterranean and the Black Sea. Many cities and places along the coasts preserved memories and cults connected with the passage of the ship Argo and its heroes. Libations and heroic sacrifices were rendered to him, and before departures by sea the sea divinities were honoured, as sailors did in memory of that first great expedition.',
    adesso: 'Honour him as patron of shared projects, of journeys and of teamwork, invoking him when you must begin an undertaking no one could accomplish alone. His story teaches that the success of a great project depends on knowing how to gather the right people and lead them through the trials. Ask him for the ability to inspire and coordinate those at your side towards a common goal. He is the patron of those who set sail together.',
  },
};
