export default {
  estia: {
    n: 'Hestia', ep: 'of the Hearth',
    intro: 'Hestia is the gentlest and most revered of the Olympian gods, the first born of Kronos and Rhea and therefore, by a symmetry of myth, also the last to be given back to the light. A virgin by choice, she refused marriage to Poseidon and to Apollo and asked Zeus for the privilege of remaining untouched and of sitting at the centre of the house, keeper of the flame. She performs no feats and lives through no adventures: her greatness is steadiness, the fire that never goes out and that holds family and city together. Every household hearth and every public Prytaneion was her living temple, and from that fire distant colonies were kindled like branches of a single stock. For this she received the first and the last libation of every rite: before her no god, after her no prayer.',
    dom: ['Hearth and sacred fire', 'Home and family', 'Community and civic life'],
    sim: ['Hearth', 'Flame', 'Circle'],
    off: ['The first and last libation of every rite', 'Oil', 'Sweet wine', 'Incense'],
    allora: 'Hestia received the first and the last portion of every sacrifice, according to the formula "from Hestia one begins". In the Prytaneion of every city burned a public fire that was never allowed to die, the heart of the community: when a colony was founded, an ember was carried from it, so that the new city remained bound to the mother country by the same hearth.',
    adesso: 'Light a dedicated candle at the beginning of every practice and greet her again at the end, granting her the first and the last place. Keep your sacred corner tidy and clean: that is her hearth, and its order is already a form of devotion.',
    inno: 'Hestia, keeper of the sacred hearth of gods and of mortals, to you the first and the last offering.',
  },

  zeus: {
    n: 'Zeus', ep: 'King of the gods',
    intro: 'Zeus is the lord of the sky and the guarantor of cosmic order, the last son of Kronos, taken by Rhea from his father’s hunger and hidden on Crete until he was strong enough to free his siblings and overthrow the Titans. From that victory he inherited the thunderbolt, forged by the Cyclopes, and sovereignty over the divine and human worlds. Yet he is not power alone: he is the god of justice (Dike sits beside him), of oaths, of hospitality and of the protection of the home. Under his many epithets — Xenios who watches over the stranger, Herkeios who guards the enclosure, Ktesios who fills the storeroom — the Greek felt him present at every threshold and in every pact. Feared for the thunder, he was invoked above all as the one who holds together the unwritten laws of living side by side.',
    dom: ['Sky, thunder and order', 'Justice and oaths', 'Hospitality and protection of the home'],
    sim: ['Thunderbolt', 'Eagle', 'Oak', 'Sceptre'],
    off: ['Incense', 'Wine', 'Barley cakes', 'For Zeus Ktesios: a jar with water, oil and fruit'],
    allora: 'As Ktesios he protected the storeroom, kept in a sacred jar (the kadiskos) filled with water, oil and fruit; as Herkeios he presided over the enclosure and the courtyard of the house, with an altar at its centre; as Xenios he watched over guest and stranger, making hospitality a sacred duty whose violation offended him directly.',
    adesso: 'Place a small jar in your pantry in honour of Zeus Ktesios, renewing it from time to time, as a sign of and a request for the prosperity of the house. Invoke him for justice, for protection, and at the moments of great decisions, when firmness and measure are needed.',
    inno: 'Zeus most high and glorious, lord of the sky and keeper of the house, watch over us.',
  },

  era: {
    n: 'Hera', ep: 'Queen',
    intro: 'Hera is the queen of Olympus, sister and wife of Zeus, goddess of marriage and sovereign beside the sovereign. Her majesty is that of the marriage bond and of a woman’s dignity: she presides over weddings, over faithfulness, and over the seasons of a woman’s life, from girlhood to motherhood. Myth often portrays her as jealous and implacable towards Zeus’s lovers and their offspring — from Heracles to Io — but that jealousy is the reverse side of her highest function: the guardianship of the marital order and of what is lawful. Each year, so the story goes, she became a virgin again by bathing in the spring of Kanathos, renewing her own wedding. Argos, Samos and Mycenae worshipped her as their great protectress, in temples among the oldest in Greece.',
    dom: ['Marriage and faithfulness', 'Women and family', 'Sovereignty'],
    sim: ['Peacock', 'Diadem', 'Pomegranate', 'Lily'],
    off: ['Pomegranate', 'Lilies', 'Incense', 'Wine'],
    allora: 'Hera was the protectress of the passages of a woman’s life, invoked with distinct epithets for the maiden (Parthenos), the wife (Teleia) and the widow (Chera). The Theogamia, or Hieros Gamos, celebrated her sacred wedding to Zeus, while in great sanctuaries such as the Heraion of Argos and of Samos festivals and processions were held in her honour.',
    adesso: 'Invoke her for unions and commitments, for the pacts that ask for loyalty, for dignity and self-respect, and for the protection of the family. Offer her fresh flowers — lilies above all — as a sign of respect towards her majesty.',
    inno: 'Hera of the golden throne, queen of the gods, bless the bonds and the household.',
  },

  poseidone: {
    n: 'Poseidon', ep: 'Lord of the sea',
    intro: 'Poseidon is the mighty lord of the sea, brother of Zeus and of Hades, to whom the waters fell by lot when the three divided the world. He wields the trident with which he raises storms, splits rocks and shakes the earth: for this he is called Enosichthon, "the earth-shaker", cause of earthquakes as well as of waves. His temper is impetuous, capable of long angers — such as the one against Odysseus — but he is also the giver of the horse and patron of horsemen. He contended with Athena for the possession of Athens by making a spring gush from the rock of the Acropolis. Sailors and voyagers appeased him before every crossing, knowing that calm and shipwreck alike depended on his will.',
    dom: ['Sea and waters', 'Earthquakes and storms', 'Horses'],
    sim: ['Trident', 'Horse', 'Dolphin', 'Bull'],
    off: ['Sea water', 'Wine', 'Barley', 'Cakes'],
    allora: 'Poseidon was appeased with offerings and libations before every sea voyage, gifts being cast among the waves to secure a quiet passage. The Poseidea honoured him in the month dedicated to him, and the eighth day of every month was sacred to him; great games in his honour were held at the Isthmus of Corinth.',
    adesso: 'Offer him something before a journey, especially by sea, or when the "waters" of your life turn rough and unpredictable. Pour water or wine asking for steadiness and safe passage through storms, whether inner or outer.',
    inno: 'Poseidon, shaker of the earth, lord of the waters, grant calm and safe passage.',
  },

  ade: {
    n: 'Hades', ep: 'Lord of the Underworld',
    intro: 'Hades is the silent lord of the realm of the dead, elder brother of Zeus, to whom the world below fell by lot. His name means "the Unseen", and indeed he owns a helm that makes its wearer invisible; but the Greeks preferred to call him Plouton, "the Rich One", because from the earth come metals, harvests and every wealth. He is not an evil god: he is just and unbending, keeper of an order from which no one can escape. Myth binds him forever to Persephone, whom he carried off and made his queen, giving rise through her seasonal return to the cycle of the seasons. Feared and honoured with caution, he was the god one turned to for mourning, for memory, and for deep transformations.',
    dom: ['The underworld and the dead', 'Ancestors and memory', 'Wealth beneath the earth and transformation'],
    sim: ['Helm of invisibility', 'Cornucopia', 'Cypress', 'Narcissus'],
    off: ['Libations poured onto the ground (honey, water, wine)', 'Narcissus', 'Cypress', 'Offerings that are not tasted'],
    allora: 'Hades was honoured with chthonic rites, distinct from the Olympian ones: offerings were directed downwards, poured onto the ground or into pits, often at night, and the victims were dark in colour. His name was spoken with caution, and he was usually called by propitiatory names such as Plouton, "the Rich One", so as not to draw his attention.',
    adesso: 'Honour him in times of mourning, in remembering ancestors and those who are gone, and at the great passages that ask you to let something go. Pour a libation onto the ground — honey, water or wine — with respect and without tasting it, for it is entirely his.',
    inno: 'Hades, who receive every life in its time, be gentle with those we remember.',
  },

  apollo: {
    n: 'Apollo', ep: 'Phoibos, the Shining One',
    intro: 'Apollo is the shining god of light, music and prophecy, son of Zeus and Leto and twin brother of Artemis, born on the floating island of Delos. He is the most Greek of the gods: he embodies measure, harmony and knowledge of what is to come. At Delphi, after killing the serpent Python, he founded his oracle, the most authoritative of the ancient world, where the Pythia pronounced his responses. With the lyre he gives music; with the silver bow he strikes from afar, bringing plague or healing, for he is at once the god who sends and the god who cures. Radiant and unpredictable, he presides over prophecy, purification, youth and poetic inspiration: his "know thyself", carved at Delphi, sums up the Greek ideal of clarity.',
    dom: ['Light, music and prophecy', 'Healing and purification', 'Youth and inspiration'],
    sim: ['Lyre', 'Bow', 'Laurel', 'Swan'],
    off: ['Laurel', 'Incense', 'Honey', 'Cakes', 'Oil'],
    allora: 'As Agyieus he protected doorways and streets, represented by a conical pillar set before the houses. He was said to have been born on the seventh day of Thargelion, and the seventh of every month was sacred to him; at Delphi and Delos great festivals, oracles and choral songs celebrated his radiant presence.',
    adesso: 'Invoke him for inspiration, for the healing of body and spirit, and for clarity in difficult choices. Place a laurel leaf at the entrance of your home and offer him music — played, or listened to with full attention — as a gift he welcomes.',
    inno: 'Apollo of the silver bow, light that heals and inspires, illuminate my path.',
  },

  artemide: {
    n: 'Artemis', ep: 'Lady of the wild',
    intro: 'Artemis is the virgin huntress, mistress of the wild lands, of animals and of the moon, daughter of Zeus and Leto and twin sister of Apollo. Born first, according to the story she helped her mother give birth to her brother, and so became the protectress of women in labour while remaining herself untouched and free. She roams the woods with her bow and her following of nymphs, defending the purity of unspoiled places: woe to those who offend her, like Actaeon, turned into a stag and torn apart by his own hounds for having seen her bathing. She is an ambivalent and powerful goddess, who watches over the young of every kind yet can also strike with sudden arrows. To her girls entrusted themselves before marriage and women at the moment of childbirth, in life’s most delicate passages.',
    dom: ['Hunting and wild nature', 'Moon and animals', 'Protection of girls and of women in labour'],
    sim: ['Bow', 'Doe', 'Crescent moon', 'Cypress'],
    off: ['Moon-shaped cakes (amphiphontes)', 'Fruit', 'Wild herbs', 'Incense'],
    allora: 'Artemis was the protectress of the passages of female life and of the growth of the young: at Brauron little girls, the "bears" of Artemis, served her before entering adulthood. She was said to have been born on the sixth day of Thargelion, and the sixth of every month was sacred to her; at Ephesus her great temple was one of the wonders of the world.',
    adesso: 'Invoke her for independence, inner strength and the bond with wild nature. Dedicate to her a walk among trees or by moonlight, and offer her fruit or gathered herbs, acknowledging her lordship over untouched places.',
    inno: 'Artemis the huntress, lady of the moon and of the woods, guard those who walk alone.',
  },

  dioniso: {
    n: 'Dionysus', ep: 'Lyaios, the Liberator',
    intro: 'Dionysus is the god of wine, ecstasy and transformation, son of Zeus and of the mortal Semele, the only Olympian born of a human mother. Snatched from the womb of his thunderstruck mother and sewn into Zeus’s thigh until he came to term, he carries in myth the mark of the double birth and of rebirth. He is the god who loosens — Lyaios, the Liberator — who with wine slackens the chains of reason and opens the doors of ecstasy, but who is also terror to those who refuse him, as the end of Pentheus shows. His train of Maenads and satyrs roams the mountains in sacred intoxication; his is the energy of the vine that dies in winter and is reborn in spring. God of theatre and of the festive community, he teaches that shared joy is itself a sacred way.',
    dom: ['Wine and ecstasy', 'Theatre and liberation', 'Rebirth and vegetation'],
    sim: ['Vine', 'Ivy', 'Thyrsus', 'Panther', 'Mask'],
    off: ['Wine', 'Grapes', 'Ivy', 'Figs'],
    allora: 'The Anthesteria celebrated the opening of the new wine and the return of the souls; the Lenaia and the Great Dionysia joined processions, wine and theatrical performances, for from the choral lyric in his honour tragic and comic theatre were born. He was the god who dies and is reborn like the vine, and his festivals renewed the community’s bond with the cycles of life.',
    adesso: 'Invoke him for joy, for release from rigidity and for artistic expression. Share a cup of wine — or of grape juice — with someone, remembering that the first libation is his, and let his energy loosen a knot that binds you.',
    inno: 'Dionysus who loosen every knot, gift of joy and of rebirth, be with us.',
  },

  ermes: {
    n: 'Hermes', ep: 'Messenger',
    intro: 'Hermes is the messenger of the gods and the most versatile of the Olympians, son of Zeus and the nymph Maia, born in a cave of Arcadia. On his very first day of life, according to the Homeric hymn, he invented the lyre from a tortoise shell and stole Apollo’s cattle, showing from the start his cunning, inventive nature and his love of crossed boundaries. With winged sandals and the caduceus he passes every threshold: between gods and mortals, between waking and dream, between the living and the dead, whom he escorts to the beyond as Psychopompos. He is patron of travellers, merchants, orators and thieves alike, god of sudden luck and of effective speech. Wherever there are roads, exchanges and encounters, there is his presence.',
    dom: ['Travel, boundaries and communication', 'Trade and luck', 'Guide of souls'],
    sim: ['Caduceus', 'Winged sandals', 'Rooster', 'Tortoise'],
    off: ['Incense', 'Honey', 'Cakes', 'Coins for luck'],
    allora: 'The herms, stone pillars topped with the god’s face, marked doorways, roads and crossroads as a sign of his protecting presence, and a chance find along the way was called a hermaion, "a gift of Hermes". The fourth day of every month was sacred to him, and as god of the marketplace he watched over the honesty of exchanges.',
    adesso: 'Invoke him before a journey, an interview or the sending of an important message, when the right word and open roads are needed. Offer him a little honey or leave a coin as a token, asking for good fortune in meetings and in transitions.',
    inno: 'Hermes of the swift feet, guide of wayfarers and of words, open the roads before me.',
  },

  demetra: {
    n: 'Demeter', ep: 'Mother of the grain',
    intro: 'Demeter is the great Mother of grain and agriculture, she who taught humankind to till the earth and to feed on bread. Sister of Zeus, her most famous myth is her grief for her daughter Persephone, carried off by Hades into the underworld: in her desperate search she abandoned her gifts, and the earth grew barren until her daughter’s return was granted. But because Persephone had tasted the seeds of the pomegranate, she had to spend part of the year below — and so the seasons were born, the winter of mourning and the spring of return. On her journey Demeter halted at Eleusis, where she founded the Mysteries that promised the faithful a hope beyond death. She is the goddess of nourishment and of cycles, who teaches how from what seems lost life can be reborn.',
    dom: ['Grain, agriculture and harvest', 'Motherhood and the cycles of life', 'Mysteries'],
    sim: ['Ears of wheat', 'Poppy', 'Torch', 'Pig'],
    off: ['Wheat', 'Barley', 'Bread', 'Fruit', 'Honey'],
    allora: 'The Eleusinian Mysteries, the most famous and most secret of ancient Greece, bound her myth with Persephone to the hope of a better lot after death, and those initiated kept silence about them for the whole of their lives. The Thesmophoria, festivals reserved for women, celebrated the fertility of the earth and the cycle of the seasons.',
    adesso: 'Invoke her for nourishment, for the natural cycles of life, and in times of mourning and rebirth, when something ends in order to return in another form. Offer her bread and seeds, and honour with awareness both what is ending and what promises to come back.',
    inno: 'Demeter who nourish the earth and the heart, bless the harvest and those who await a return.',
  },

  atena: {
    n: 'Athena', ep: 'Lady of wisdom',
    intro: 'Athena is the goddess of wisdom, strategy and craft, born in prodigious fashion from the head of Zeus, already grown and armed, after her father had swallowed her mother Metis. A virgin like Artemis, she embodies nonetheless another form of power: that of applied intelligence, of war waged with measure and justice — unlike the blind fury of Ares — and of the ingenuity that creates. She gave humankind the olive tree, winning thereby the contest with Poseidon for the patronage of Athens, the city that bears her name. She protects craftsmen, weavers, and level-headed heroes such as Odysseus, whom she guides by counsel rather than by force. With the owl, the olive and the aegis, she is at once the lucid mind of strategy and the skilled hand at the loom.',
    dom: ['Wisdom and strategy', 'Craft and weaving', 'Justice and defence'],
    sim: ['Owl', 'Olive tree', 'Aegis', 'Helmet', 'Spear'],
    off: ['Olive oil', 'Cakes', 'Incense', 'Wool and yarn'],
    allora: 'Athena was the patroness of Athens, celebrated at the great Panathenaia, when to her ancient statue was offered a peplos woven and embroidered by the women of the city and carried in solemn procession up the Acropolis, as far as the Parthenon. The third day of every month was sacred to her, and with Hephaestus she was honoured as the protectress of craftsmen.',
    adesso: 'Invoke her for study, for work, for wise decisions and for creative projects that call for method and ingenuity. Pour a thread of olive oil on the altar, or dedicate to her the first gesture of a work made with the hands and the mind.',
    inno: 'Athena of the bright eyes, give me wisdom in acting and measure in judging.',
  },

  ares: {
    n: 'Ares', ep: 'Lord of war',
    intro: 'Ares is the god of war in its rawest and most impetuous form, son of Zeus and Hera, the embodiment of the fury of battle and of courage that knows no hesitation. Where Athena stands for strategy and the just war, Ares is the ardour of combat itself, raw force, the tumult of blood and iron. The Greeks regarded him with fear and ambivalence: necessary for the defence of the city and its borders, yet dangerous when his fury broke loose without measure. Myth binds him to Aphrodite in a famous love, as if to suggest that passion and conflict are kindred forces. Honoured more openly in lands such as Thrace and at Sparta, he remained nonetheless the god from whom one asked boldness at the moment of danger.',
    dom: ['Courage and strength', 'Defence and discipline', 'Boundaries'],
    sim: ['Spear', 'Helmet', 'Dog', 'Boar'],
    off: ['Incense', 'Wine'],
    allora: 'Ares was feared and at the same time invoked for victory and for the defence of borders, especially among warlike peoples such as the Thracians and the Spartans, who made him a patron of military valour. His was a raw force to be channelled by discipline, and men turned to him before the clash to obtain boldness and steadiness.',
    adesso: 'Invoke him for courage, to defend your personal boundaries, and to face what frightens you without giving way. Ask him for the discipline that turns impulse into useful strength, keeping you steady in the face of trials.',
    inno: 'Ares of the steady heart, grant me courage and firmness in defending what is right.',
  },

  afrodite: {
    n: 'Aphrodite', ep: 'Lady of love',
    intro: 'Aphrodite is the goddess of love, beauty and desire, born according to the oldest account from the foam of the sea near Cyprus, rising already radiant from the waves. She is a cosmic force before she is a personal divinity: the power that attracts and joins, that drives beings towards one another and keeps the world in harmony. No one, mortal or immortal, escapes her enchantment, and whoever neglects her — like Hippolytus — pays the price. Her magic girdle instils irresistible desire; her beauty unleashed the Trojan War. But Aphrodite is not passion alone: as Ourania she presides over the highest and most spiritual love, as Pandemos over the affection that holds a community together. Roses, myrtle and doves are dear to her, and with them the grace that makes life lovable.',
    dom: ['Love and beauty', 'Desire and pleasure', 'Harmony and the sea'],
    sim: ['Dove', 'Rose', 'Myrtle', 'Shell', 'Apple'],
    off: ['Roses', 'Myrtle', 'Honey', 'Incense', 'Scented water'],
    allora: 'Aphrodite was honoured under different aspects: as Ourania she stood for celestial and elevated love, as Pandemos for the concord and affection that bind the community of the city. The fourth day of every month was dear to her, and her most famous sanctuaries stood at Cyprus, Kythera and Corinth.',
    adesso: 'Invoke her for love, self-worth, relationships and beauty in every form. Offer her fresh flowers, a perfume or scented water, and accompany the rite with a concrete act of care towards yourself, for this too is devotion.',
    inno: 'Aphrodite of the sweet smile, bring me love, harmony and grace.',
  },

  efesto: {
    n: 'Hephaestus', ep: 'Divine smith',
    intro: 'Hephaestus is the god of fire and of the forge, the divine artificer who fashions the most marvellous works of Olympus. Son of Hera — who according to some conceived him alone — he was born lame, and for this he was hurled down from the sky; yet it is precisely his imperfection that makes him, among the shining gods, the most human and the most industrious. From his anvil come the thunderbolts of Zeus, the arms of Achilles, the thrones and palaces of the gods, and even golden automata that assist him at his work. Husband of Aphrodite, he joins craft to beauty in symbol. He is the god who transforms raw matter with the patience of fire and the labour of the hands, patron of all who create and repair, and who draw lasting works out of difficulty.',
    dom: ['Fire and the forge', 'Metalwork and craft', 'Invention and perseverance'],
    sim: ['Anvil', 'Hammer', 'Tongs', 'Fire'],
    off: ['Incense', 'Oil', 'Wine'],
    allora: 'Hephaestus was the god of creative fire and of manual work, especially venerated at Athens and on Lemnos, the island where he was said to have fallen. Together with Athena he was patron of craftsmen and smiths, celebrated at the Chalkeia, the festival of metalworkers, and at the Hephaisteia with torch races.',
    adesso: 'Invoke him for handcraft, for projects to be built and things to be mended, and for every undertaking that requires patience and skill. Ask him for the perseverance that turns limits and difficulties into solid, well-made work.',
    inno: 'Hephaestus the untiring, master of fire and of ingenuity, bless the work of my hands.',
  },
};
