export default {
  muse: {
    n: 'The Muses', ep: 'Goddesses of inspiration and the arts',
    intro: 'Daughters of Zeus and Mnemosyne, Memory, the nine Muses were born in Pieria, at the foot of Olympus, after nine nights of love, and ever since they have been the living spring of all song. Each presides over an art or a science — Calliope over epic poetry, Clio over history, Erato over love lyric, Euterpe over music, Melpomene over tragedy, Polyhymnia over sacred hymns, Terpsichore over dance, Thalia over comedy, Urania over astronomy — and together they form the choir that gladdens the tables of the gods. It is to them that Homer and Hesiod ask to sing, for without their voice the poet is mute: it is the Muses who "remember" what a mortal could not know. They danced on Helicon and Parnassus, by the springs of Hippocrene and Castalia, where water sprung from the hoof of Pegasus granted poetic inspiration. Stern keepers of the true and the beautiful, they could punish anyone who dared challenge them, like Thamyris of Thrace, blinded for his presumption. In Greek culture they embodied the very idea that human creation is a divine gift, not a mere skill.',
    dom: ['Music, song and dance', 'Poetry, eloquence and letters', 'Astronomy and science', 'Inspiration and memory'],
    sim: ['Lyre and flute', 'Scrolls and stylus', 'Laurel crown', 'Celestial globe'],
    off: ['Libations of water, milk and honey', 'Hymns and songs', 'Creative works dedicated to them'],
    allora: 'Originally from Pieria, the Muses were venerated above all on Helicon in Boeotia, where their sacred grove stood with its holy springs, and on Parnassus near Delphi. Poets opened their works with an invocation to the Muses, and in the sanctuaries bloodless libations of water, milk and honey were offered to them. Around their cult flourished the Mouseia, festivals with poetic and musical contests; it is no accident that the "museum" was born as a place consecrated to them.',
    adesso: 'Invoke them at the start of any creative work, of a course of study or of a piece of research, asking for clarity and inspiration. Dedicate to them the works you bring to completion — a written page, a melody, a project — as a token of gratitude. A small altar with laurel, a notebook and a candle can accompany the moment you sit down to create. They are the ideal patrons of writers, artists, musicians and scholars.',
  },

  'cariti-grazie': {
    n: 'The Charites (Graces)', ep: 'Goddesses of grace and joy',
    intro: 'The three Charites — Aglaia, Splendour, Euphrosyne, Gladness, and Thalia, festive Abundance — are the goddesses who give life its luminous charm. Daughters of Zeus and the Oceanid Eurynome, they embody everything that makes existence sweet: beauty, gratitude, the pleasure of company, the charm of kindly gestures. They dance in a ring, holding hands, the perfect image of the reciprocity of gift and favour that circulates among those who care for one another. Companions and handmaids of Aphrodite, whose body and robe they adorn, and close also to Apollo and the Muses, they lend grace to every art and every feast. The Greek word charis that gives them their name means grace, favour and gratitude all at once: without the Charites no gift would be welcome and no work of art complete. They were the breath of joy that accompanied banquets, weddings and celebrations.',
    dom: ['Grace and beauty', 'Joy, festivity and dance', 'Adornment and the pleasure of company', 'Gratitude and courtesy'],
    sim: ['Roses and myrtle', 'The ring dance', 'Youthful nakedness'],
    off: ['Flowers and roses', 'Perfumes', 'Banquets and wine', 'Music and dance'],
    allora: 'Their oldest cult had its seat in Boeotia, at Orchomenos, where they were venerated in the form of sacred stones fallen from the sky and the Charisia festivals were celebrated in their honour, with night dances and musical contests. They were honoured also at Sparta, at Athens and in many sanctuaries as companions of other divinities, since no rite was complete without their grace. Tradition always associated them with choral dance and festive company.',
    adesso: 'Honour them by cultivating beauty, gratitude and generosity in your relationships: a flower given, a gesture of hospitality, a sincere thank-you are already offerings they welcome. Make your home inviting and lay the table with care when you receive someone, remembering that shared pleasure is sacred. Cultivate reciprocity: to receive with grace and to give back with joy is their teaching. They are patrons of elegance, conviviality and courtesy.',
  },

  ore: {
    n: 'The Horai', ep: 'Goddesses of the seasons and of order',
    intro: 'The Horai are the keepers of the time that ripens and returns: daughters of Zeus and Themis, Law, they preside over the cycle of the seasons and over the order that governs nature and human life alike. In their most famous form they are three — Eunomia, Good Order, Dike, Justice, and Eirene, Peace — showing how the good governance of time and that of society are one and the same. They fling open and close the gates of Olympus, gathering or dispersing the clouds, and they accompany the flowering and fruiting of the earth. It was they who led the divinities of the natural cycles and marked the passage from sowing to harvest. The Greeks felt them near whenever nature kept to its right rhythm: the spring that returns, the crop that ripens, the peace that follows order. They guarded the idea that time is not chaos, but measure and harmony.',
    dom: ['The seasons and the cycle of time', 'Natural and cosmic order', 'Justice and good governance', 'Peace and social harmony'],
    sim: ['Seasonal flowers and fruits', 'The gates of Olympus', 'Cornucopia', 'Garlands'],
    off: ['Seasonal first fruits', 'Flowers', 'Libations', 'Crowns'],
    allora: 'They guarded the gates of Olympus and regulated the seasons and the cosmic order, and for this they were dear above all to farmers, who depended on them for the harvest. They received cult at Athens, where their names were linked to good civic government, and in places such as Olympia and Argos. To them were offered the first fruits of every season, flowers and crowns, in thanks for the fertile rhythm of the year.',
    adesso: 'Honour them by living in tune with the rhythms of the seasons: celebrate the solstices and the equinoxes, eat the fruits of the right season, respect the phases of your life without forcing them. Every act of justice, punctuality and harmony is homage to their order. Devote a moment to putting your day and your commitments in order, recognising that time well spent is sacred too. They are patrons of balance and measure.',
  },

  'moire-parche': {
    n: 'The Moirai (Fates)', ep: 'Goddesses of destiny',
    intro: 'The Moirai are the three sisters who hold the life of every being in their hands, the gods included: Klotho, the Spinner, who spins the thread of existence; Lachesis, who measures its length and allots the lot; and Atropos, the Inflexible, who cuts it with her shears when the hour has come. Born according to some from Night, according to others from Zeus and Themis, they embody the deepest law of the cosmos, that "portion" (moira) which falls to each and which no one may overstep. Even the gods bow to their decree, and Zeus himself is called Moiragetes, "he who leads the Moirai", not "he who commands them". Present at the birth of every child, they sing out its destiny and fix it forever. They are not cruel, but impartial: they distribute good and evil, life and death, with inflexible justice. The Greeks feared and respected them as the very voice of necessity.',
    dom: ['The destiny and lot of each person', 'Birth and death', 'The measure of a lifetime', 'Cosmic necessity'],
    sim: ['Spindle and distaff', 'The thread of life', 'Scales', 'Shears'],
    off: ['Libations of honey and water', 'Flowers', 'Cakes', 'Offerings at births'],
    allora: 'Honoured as the dispensers of fate from birth to death, they had sanctuaries and altars at Corinth, Sparta, Olympia, Thebes and Delphi, often beside Zeus Moiragetes. Bloodless libations of honey and water, flowers and cakes were offered to them, especially at births, when a favourable lot was invoked for the newborn. They were invoked also at the solemn moments of marriage and death, the great passages over which they presided.',
    adesso: 'Honour them at life’s great passages — a birth, a bereavement, a decisive turn — recognising what is in your hands and what is not. Cultivate the serenity to accept the inevitable, distinguishing it from the courage to act where you can still choose. Light a candle and honour your ancestors, remembering that you are part of a thread that comes from far away. They are patrons of awareness of time and of the weight of choices.',
  },

  nike: {
    n: 'Nike', ep: 'Goddess of victory',
    intro: 'Nike is the winged goddess who descends to crown the one who triumphs, swift as a beat of wings and bright as glory itself. Daughter of the Titan Pallas and of the marsh Styx, together with her siblings Zelos, Kratos and Bia she took Zeus’s side in the war against the Titans, and for this the king of the gods kept her forever beside him. Tradition remembers her as the charioteer of his chariot and his inseparable companion, so that she often appears in the very hand of Zeus or of Athena, a small figure holding out the crown to the victor. She flies over battlefields and stadiums, poised an instant before alighting on the head of one who has earned the triumph, in war as in athletic games and poetic contests. She is not the strength that wins, but the shining and fleeting moment of victory consecrated. The Greeks felt her near in every effort crowned with success, and admired her light grace.',
    dom: ['Victory in war', 'Triumph in athletic games', 'Success in artistic contests', 'Glory and recognition'],
    sim: ['Wings', 'Laurel crown and fillet', 'Palm branch', 'Lyre'],
    off: ['Crowns and fillets', 'Dedicated trophies', 'Libations of victory', 'Songs of celebration'],
    allora: 'Winged goddess of victory and companion of Athena, Nike crowned the victors of wars and games. Her most famous sanctuary is the temple of Athena Nike on the Acropolis of Athens, where she was venerated in her "wingless" form (Aptera), so that victory might never leave the city. Trophies, crowns and songs of triumph were dedicated to her, and her image adorned monuments raised in memory of battles won.',
    adesso: 'Invoke her before an important challenge — an exam, a race, an interview, a goal long pursued — asking her for the clarity and the drive to give your best. When you win something, dedicate it to her with gratitude rather than arrogance, remembering how precious and fleeting victory is. A small laurel or a token of your achievement laid on the altar honours her. She is the patron of sport, of determination and of goals attained.',
  },

  tyche: {
    n: 'Tyche', ep: 'Goddess of fortune',
    intro: 'Tyche is the unstable and powerful goddess who holds the rudder of chance, able to raise a person to wealth or overturn them into misery with a single turn of her wheel. Held to be daughter of Ocean or of Zeus, she presides over fortune understood as what happens without merit or fault, the pure unforeseen of luck. In one hand she holds the cornucopia brimming with goods, in the other the rudder with which she steers human affairs, and beneath her foot sometimes the sphere or the wheel, the image of her changeable and never settled nature. She dispenses Eutychia, good luck, but misfortune too, for fortune knows no loyalty. In the Hellenistic age her cult grew enormously: every city wanted its own protecting Tyche, crowned with walls, guarantor of its prosperity. The Greeks felt her wherever destiny showed itself capricious, and knew she was to be treated with respect and without presumption.',
    dom: ['Fortune and chance', 'Prosperity and wealth', 'Changeable luck', 'Protection of cities'],
    sim: ['Rudder', 'Cornucopia', 'Wheel or sphere', 'Mural crown'],
    off: ['Libations', 'First fruits and coins', 'Incense', 'Cakes'],
    allora: 'Venerated as the giver of fortune and prosperity, Tyche had cult at Pharai, Smyrna, Sikyon, Athens and Olympia, and as the Tyche of a city she became protectress of whole cities, with the mural crown upon her head. She was often paired with Nemesis, who balanced her gifts and prevented excessive fortune from turning into presumption. Libations, first fruits, coins and incense were offered to her, in thanks and in request for her favour.',
    adesso: 'Honour her by meeting the changes of fortune with balance, neither exulting in good luck nor despairing in bad. In fortunate moments, offer a small gesture of gratitude — a coin given away, a symbolic offering — recognising that not everything depends on you. Cultivate hope and flexibility in the face of the unforeseen, remembering that the wheel always turns. She is the patron of accepting chance and of trust in the future.',
  },

  nemesi: {
    n: 'Nemesis', ep: 'Goddess of just retribution',
    intro: 'Nemesis is the goddess who watches over the balance of the world and tolerates no excess: her name derives from the verb meaning "to distribute what is due", for it falls to her to give each back their rightful share. Daughter of Night, she embodies divine indignation against presumption, hybris, that boundless pride with which mortals forget their limits and challenge the gods. When someone’s fortune grows beyond measure, or when someone enjoys an undeserved good, it is Nemesis who lowers the scales and brings things back to their order. Winged, with bridle and whip in hand, she pursues whoever runs too high and calls them back to measure. Myth also binds her to the birth of Helen, brought forth from an egg after Zeus pursued her by changing into a swan. The Greeks feared her as the voice that reminds every fortunate person: nothing in excess.',
    dom: ['Divine retribution', 'Punishment of presumption (hybris)', 'Balance and right measure', 'Moral indignation'],
    sim: ['Wings', 'Bridle and whip', 'Scales', 'Apple branch'],
    off: ['Libations', 'Branches', 'Incense', 'Acts of measure and humility'],
    allora: 'Her most famous sanctuary stood at Rhamnous in Attica, where the statue carved by Agorakritos, a pupil of Phidias, was venerated — made according to tradition from the marble the Persians had brought to raise a monument to the victory they expected, a victory their own hybris turned into defeat. The Nemesia were celebrated there and libations, branches and incense were offered to her. She was often invoked beside Tyche, to temper the excesses of fortune.',
    adesso: 'Honour her by cultivating measure, humility and a sense of justice, recognising your limits and resisting the temptation of arrogance. When life smiles on you, remember not to grow proud; when you suffer a wrong, trust to the restoring of balance rather than to blind revenge. A moment of sobriety and measured gratitude is already homage to her. She is the patron of inner balance and of respect for limits.',
  },

  eros: {
    n: 'Eros', ep: 'God of love and desire',
    intro: 'Eros is the force that kindles passion and moves all things towards union: in the oldest cosmogonies he is one of the first powers born from Chaos, a primordial principle that drives beings to love and to beget. The more widespread tradition, however, makes him the beautiful son of Aphrodite, a winged youth with laughing eyes, armed with a bow and golden arrows with which he pierces the hearts of gods and mortals, and with the torch with which he sets their desire alight. No one is safe from his shafts, and even Zeus must yield to his power; capricious and irresistible, he plays with the fortunes of lovers. His most famous myth binds him to Psyche, the mortal soul he loved in secret and who, after trials and sorrows, was made immortal and his wife forever — a tale of the love that unites desire and soul. The Greeks venerated him as the power that holds the world together and makes life worth living.',
    dom: ['Love and desire', 'The passion of hearts', 'Attraction and union', 'Bonds of affection'],
    sim: ['Bow and arrows', 'Golden wings', 'Flaming torch', 'Roses'],
    off: ['Flowers and roses', 'Libations', 'Gifts of love', 'Incense'],
    allora: 'The oldest centre of his cult was Thespiai in Boeotia, where Eros was venerated in the form of an unworked stone and the Erotidia were celebrated every four years, festivals with athletic and musical contests in his honour. He was honoured also at Athens, near the Academy, and in the wrestling schools, as a power that inspired both love and valour. Flowers, roses, libations and incense were offered to him, and lovers turned to him.',
    adesso: 'Invoke him in relationships of love and whenever you wish to cultivate passion, tenderness and a deep connection with another person. Honour him with flowers, with sincere gestures of affection and with care for your bonds, remembering that love must be nourished and not only desired. A small altar with roses and a candle can accompany your thoughts of the one you love. He is the patron of love, of desire and of the bonds of the heart.',
  },

  iris: {
    n: 'Iris', ep: 'Goddess of the rainbow and messenger',
    intro: 'Iris is the goddess who joins sky and earth, appearing as the rainbow that stretches out bright after the rain. Daughter of the Titan Thaumas and the Oceanid Elektra, and sister of the Harpies, she has golden wings and an iridescent robe, and descends swift as light to carry the messages of the Olympian gods to mortals and to the other divinities. She is above all the faithful handmaid of Hera, whose commands she carries out, but she serves all Olympus, crossing in an instant seas, mountains and even the depths of Hades, where she draws the water of the Styx by which the gods pronounce their solemn oaths. Always in motion, she has almost no myths of her own: her essence is transit, the bridge, the bond. Like the rainbow that marks the end of the storm, she brings with her a sense of hope and of reconciliation between the divine and the human. The Greeks saw her every time the sky opened in colour after the rain.',
    dom: ['The rainbow', 'Messenger of the gods', 'The bond between sky and earth', 'Communication and reconciliation'],
    sim: ['Golden wings', 'Caduceus', 'Water pitcher', 'Rainbow'],
    off: ['Wheat and honey cakes', 'Dried figs', 'Libations of water', 'Crowns'],
    allora: 'Messenger of the gods and handmaid of Hera, Iris did not have as widespread a cult as other divinities, but she was honoured in particular at Delos, where the inhabitants offered her wheat cakes kneaded with honey and dried figs. Her figure recurred in poetry and art as a link between the worlds, swift and tireless. The rainbow itself, which bore her name, was felt to be a favourable sign from her.',
    adesso: 'Honour her as the carrier of messages and connections: when you have to communicate something difficult, seek reconciliation after a quarrel or bring good news, invoke her to guide your words. She is the goddess of the hope that returns after the storm, so turn to her at times of recovery and of new beginnings. A glass of clear water offered to the light can be her simple homage. She is the patron of messengers, journeys and new beginnings.',
  },

  'agathos-daimon': {
    n: 'Agathos Daimon', ep: 'Good Spirit of the house',
    intro: 'Agathos Daimon, the "Good Spirit", is the kindly power that watches over the prosperity of the house and the good fortune of the family. Portrayed as a serpent, the animal that in Greek tradition guards places and the wealth beneath the earth, he is the household spirit above all others, guarantor of abundance and of the protection of the hearth. He has no elaborate myth: his presence is felt in daily life, in the well-being that makes a household serene. He was invoked with affection and familiarity, as a close and discreet protector. To him, at the end of the meal, the first cup of unmixed wine was poured, in a gesture of gratitude for the gifts received. He embodied the idea that every home was watched over by a good spirit, to be honoured so that fortune should not leave the threshold.',
    dom: ['Fortune of the house', 'Household protection', 'Abundance'],
    sim: ['Serpent', 'Cup of wine'],
    off: ['A libation of unmixed wine after the meal'],
    allora: 'The "good spirit" of the house was honoured on the second day of every month, dedicated to him, with a libation of pure wine, unmixed with water, poured after the meal. It was customary, once the meal was over, to offer him the first cup in token of thanks and to win good fortune for the family. His serpent image was sometimes painted in houses, in protection of the storeroom and the hearth.',
    adesso: 'Honour him with a simple toast of gratitude for your home and for good fortune: the first cup poured or dedicated to him, at the end of a meal, renews the ancient gesture. It is a concrete way of recognising and cultivating the well-being of the place you live in and of the people who share it. A grateful thought before sitting down at table, or at the end of dinner, is enough to make it a daily rite. He is the discreet patron of household prosperity.',
  },
};
